name: Clang Format Check

on:
  push:
    branches:
      - clang-format-ci
jobs:
  check_formatting:
    name: Check Code Formatting
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache clang-format dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/apt-cache
          key: clang-format-${{ runner.os }}
          restore-keys: |
            clang-format-${{ runner.os }}-

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18

      - name: Check formatting
        run: |
          clang-format --dry-run --Werror -style=file src/**/*.cpp src/**/*.h include/**/*.h
