name: Clang Format Check & Auto Fix
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  check_formatting:
    name: Check Code Formatting
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install clang-format 22
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22
      - name: Run Clang Format
        run: |
          clang-format-22 -i server/**/*.cpp server/**/*.hpp \
                           client/**/*.cpp client/**/*.hpp \
                           core/**/*.cpp core/**/*.hpp \
                           game_engine/**/*.cpp game_engine/**/*.hpp
      - name: Commit formatted code (if any)
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(format): apply clang-format"
          branch: ${{ github.head_ref }}
          file_pattern: "server/**/*.cpp server/**/*.hpp client/**/*.cpp client/**/*.hpp core/**/*.cpp core/**/*.hpp game_engine/**/*.cpp game_engine/**/*.hpp"
