name: Clang Format Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check_formatting:
    name: Check Code Formatting
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LLVM clang-format-18
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-format-18
          clang-format-18 --version

      - name: Check formatting
        run: |
          clang-format-18 --dry-run --Werror -style=file server/**/*.cpp server/**/*.hpp client/**/*.cpp client/**/*.hpp
